# Generated by Django 3.2 on 2022-01-24 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('ingredients', models.TextField()),
                ('method', models.TextField()),
                ('author', models.ForeignKey(default='Some String', on_delete=django.db.models.deletion.CASCADE, related_name='submitted_recipes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
