# Generated by Django 3.2 on 2022-01-19 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_recipe_form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='createrecipe',
            name='title',
            field=models.CharField(default=False, max_length=200, unique=True),
        ),
    ]
