# Generated by Django 3.2 on 2022-01-19 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_recipe_form', '0002_createrecipe_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createrecipe',
            name='title',
            field=models.CharField(default=False, max_length=200),
        ),
    ]
