# Generated by Django 3.2 on 2022-01-24 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_recipe_form', '0003_alter_createrecipe_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createrecipe',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
