# Generated by Django 3.2 on 2022-01-18 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_alter_post_ingredients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='post',
            name='method',
        ),
    ]
